version: "3"

services:
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  java:
    container_name: 'spring-chat-app'
    build:
      context: .
    ports:
      - '8081:8081'
    volumes:
      - ../../lib/services:/opt/app/lib/services